# frequency_sweep.py
# Is there cointegration at HIGHER FREQUENCY than daily?
#
# THE POINT, AND WHY THIS SCRIPT IS NOT A BACKTEST
# The daily study is dead: p-values across ~215 sector pairs came back UNIFORMLY
# distributed, which is the signature of "nothing here". Zero pairs survived a
# multiple-testing correction. The obvious next hypothesis is that daily closes are
# simply too coarse -- mean reversion in liquid futures is generated by market-making
# and liquidity provision, which operate over MINUTES TO HOURS, and there was never a
# strong reason to expect it to survive out to a daily horizon.
#
# The WRONG way to test that is to rebuild the pipeline at hourly frequency, run a
# backtest, and look at the Sharpe. That is exactly how the fake 0.87 happened. A
# backtest will ALWAYS produce a number, and if you keep changing the frequency until
# one looks good, you have fitted to the test set with extra steps.
#
# The RIGHT way is the p-value histogram, run FIRST, before any backtest exists.
# Under the null -- nothing is cointegrated -- p-values are UNIFORM on [0, 1]. So:
#
#     REAL SIGNAL   = a SPIKE near zero, tail stays roughly uniform
#     NOTHING THERE = flat. Which is what daily gave us.
#
# If the hourly histogram is also flat, the hypothesis is dead and you stop. No
# backtest, no Sharpe, no temptation. If a spike appears, THEN it is worth building.
#
# WHAT CHANGES AT HIGHER FREQUENCY
#   more bars -> ADF has far more POWER. It is much less likely to MISS genuine mean
#   reversion. This is a FAIRER test, not a friendlier one -- coint() still uses the
#   correct Phillips-Ouliaris critical values, so more data does not mean more false
#   positives. If the histogram is still uniform with 6x the observations, that is a
#   much stronger negative result than the daily one.
#
# WARNING -- READ BEFORE RUNNING
#   This resamples the raw 1-min CSVs, so it is SLOW and memory-hungry. Start with
#   TICKER_LIMIT set low and freq="1h". Do not jump straight to "5min" on 164 tickers.
#
# Read-only. Changes nothing. Run from the repo root:
#   python3 -m verification_scripts.frequency_sweep

import sys, os
sys.path.append(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))

import numpy as np
import pandas as pd

from data_layer import load_panel
from candidate_pairs.create_pairs import all_pairs
from candidate_pairs.cointegration import (
    hedge_ratio, correlation, pair_is_valid, coint_pvalue,
)

FOLDER = "/Users/ashankawasthy/Desktop/quant_trading/derived_data/futures"

# Frequencies to compare. "1D" is the control -- it must reproduce the known result
# (uniform, ~9 pairs pass, 0 survive BH) or something is wrong with this script.
FREQUENCIES = ["1D", "1h"]

FORMATION_MONTHS = 12     # same window as the daily study, so the comparison is clean
ALPHA = 0.05
FDR_Q = 0.10

# Cap the universe while you find out how slow this is. None = all pairs.
PAIR_LIMIT = None


def benjamini_hochberg(pvals: np.ndarray, q: float) -> np.ndarray:
    """Boolean mask of which p-values survive BH-FDR control at level q."""
    n = len(pvals)
    order = np.argsort(pvals)
    thresholds = (np.arange(1, n + 1) / n) * q
    passing = np.where(pvals[order] <= thresholds)[0]
    mask = np.zeros(n, dtype=bool)
    if len(passing):
        mask[order[: passing.max() + 1]] = True
    return mask


def histogram(pvals: np.ndarray) -> None:
    """Print the p-value distribution against what UNIFORM predicts.

    THIS IS THE WHOLE DIAGNOSTIC. Uniform means the null is true, i.e. every spread is
    a random walk. A spike in the bottom bin -- and ONLY in the bottom bin -- is what
    real cointegration looks like."""
    bins = [0, 0.01, 0.05, 0.10, 0.25, 0.50, 1.01]
    labels = ["0.00-0.01", "0.01-0.05", "0.05-0.10", "0.10-0.25",
              "0.25-0.50", "0.50-1.00"]
    widths = [0.01, 0.04, 0.05, 0.15, 0.25, 0.50]
    n = len(pvals)

    counts = pd.cut(pd.Series(pvals), bins=bins, labels=labels,
                    right=False).value_counts().reindex(labels)

    print(f"\n  {'bin':>12}  {'observed':>8}  {'if uniform':>10}   distribution")
    print(f"  {'-'*12}  {'-'*8}  {'-'*10}   {'-'*40}")
    for lab, width in zip(labels, widths):
        obs = int(counts[lab])
        exp = width * n
        note = ""
        if lab == "0.00-0.01":
            if obs > 3 * exp and obs >= 8:
                note = "  <-- SPIKE. worth investigating."
            else:
                note = "  <-- no spike."
        print(f"  {lab:>12}  {obs:>8}  {exp:>10.0f}   {'#' * min(obs, 40)}{note}")


def sweep(freq: str, pairs: list) -> dict:
    tickers = sorted({t for _s, a, b in pairs for t in (a, b)})
    print(f"\n{'=' * 80}")
    print(f"FREQUENCY = {freq}")
    print(f"{'=' * 80}")
    print(f"  loading {len(tickers)} tickers at {freq}... (slow for intraday)")

    close = load_panel(FOLDER, tickers=tickers, freq=freq)

    start = close.index.min()
    cutoff = start + pd.DateOffset(months=FORMATION_MONTHS)
    formation = close[close.index < cutoff]

    bars_per_day = len(formation) / max(
        1, len(pd.Series(formation.index.date).unique()))
    print(f"  formation: {start.date()} -> {cutoff.date()}")
    print(f"  {len(formation):,} bars  ({bars_per_day:.1f} bars/day)")

    pvals, names, gated = [], [], 0
    for _sector, a, b in pairs:
        if a not in formation.columns or b not in formation.columns:
            continue
        pair = formation[[a, b]].dropna()
        if len(pair) < 100:
            continue

        beta = hedge_ratio(pair[a], pair[b])
        ok, _reason = pair_is_valid(pair[a], pair[b], beta)
        if not ok:
            gated += 1
            continue

        p = coint_pvalue(pair[a], pair[b])   # proper Engle-Granger
        if np.isnan(p):
            continue
        pvals.append(p)
        names.append(f"{a}-{b}")

    pvals = np.array(pvals)
    n = len(pvals)
    if n == 0:
        print("  no pairs survived the gate")
        return {}

    n_pass = int((pvals < ALPHA).sum())
    expected = ALPHA * n
    bh = benjamini_hochberg(pvals, FDR_Q)
    n_bh = int(bh.sum())

    print(f"\n  rejected by corr/beta gate : {gated}")
    print(f"  tested with Engle-Granger  : {n}")
    print(f"  pass p < {ALPHA}              : {n_pass}")
    print(f"  EXPECTED from chance alone  : {expected:.0f}   ({ALPHA:.0%} of {n})")
    print(f"  survive BH-FDR at q = {FDR_Q}   : {n_bh}")

    histogram(pvals)

    if n_bh:
        order = np.argsort(pvals)
        print(f"\n  the {n_bh} pairs surviving BH-FDR:")
        for i in order[:n_bh]:
            print(f"    {names[i]:<28} p = {pvals[i]:.5f}")

    return {"freq": freq, "tested": n, "pass_005": n_pass,
            "expected": round(expected, 1), "survive_bh": n_bh,
            "verdict": "SIGNAL" if n_bh > 0 else "nothing"}


if __name__ == "__main__":
    pairs = all_pairs()
    if PAIR_LIMIT:
        pairs = pairs[:PAIR_LIMIT]

    print("=" * 80)
    print("FREQUENCY SWEEP -- is there cointegration at any bar size?")
    print("=" * 80)
    print("  This is NOT a backtest. It looks only at the p-value distribution.")
    print("  Uniform  = nothing is cointegrated. Stop here.")
    print("  Spike    = something is there. THEN build the backtest.")
    print(f"\n  {len(pairs)} candidate pairs, {FORMATION_MONTHS}-month formation window")

    rows = [r for freq in FREQUENCIES if (r := sweep(freq, pairs))]

    print("\n" + "=" * 80)
    print("SUMMARY")
    print("=" * 80)
    print(pd.DataFrame(rows).to_string(index=False))

    print("\n  HOW TO READ THIS")
    print("  If pass_005 is at or below `expected` and survive_bh is 0, then that")
    print("  frequency has NOTHING. That was the daily result, and if hourly reads the")
    print("  same way, the intraday hypothesis is dead too -- with 6x the observations,")
    print("  so ADF had far more power to find something and still found nothing.")
    print("  That is a STRONGER negative result than daily, not a weaker one.")
    print("\n  Only if a frequency shows a genuine SPIKE in the bottom bin AND survives")
    print("  BH is it worth building a backtest. And even then: transaction costs at")
    print("  hourly frequency are ~6x daily turnover, and the current COST_PER_UNIT of")
    print("  0.05 is already ~1000x too small. Fix costs BEFORE trusting any Sharpe.")
