"""
data_layer.py - load NSE near-month futures (1-min bars) into a daily price panel.

Your raw files (derived_data/futures/TICKER_-I.csv) look like:
    Ticker,Date,Time,Open,High,Low,Close,Volume,Open Interest
    HDFCBANK-I.NFO,02/01/2023,09:15:59,1630.05,...

This loader:
  - reads only near-month (_-I.csv) files
  - parses the dd/mm/yyyy dates
  - compresses 1-minute bars down to ONE row per day (daily close = last
    price of the day; daily volume = sum) - much lighter to work with
  - builds a `close` panel: rows = dates, cols = tickers

Daily is the clean starting point. We can switch to finer bars later without
changing anything downstream.
"""

import os
import glob
import pandas as pd

MONTH_SUFFIX = "_-I"

def _clean_ticker(filename: str) -> str: # _ marks private helper
    """'HDFCBANK_-I.csv' -> 'HDFCBANK'.  'HDFCBANK.csv' -> 'HDFCBANK'.
    The near-month suffix is stripped if present, but is not required -- any
    filename works, the ticker is just the basename."""
    base = os.path.basename(filename) #.../futures/HDFCBANK_-I.csv -> HDFCBANK_-I.csv
    base = base.replace(".csv", "")
    base = base.replace(MONTH_SUFFIX, "")   # strip the near-month suffix if there is one
    return base 


def load_daily_close(path: str) -> pd.Series:
    """
    Reads a csv file (near-month futures CSV of 1-min bars) and  
    returns a panda series with Day and Daily close = the last traded price of the day.
    Ex. AMBER-I.csv -> 
    2025-06-27    6900.0
    2025-06-30    6812.0
    """
    df = pd.read_csv(path, usecols=["Date", "Time", "Close", "Volume"])
    # dates are dd/mm/yyyy
    df["date"] = pd.to_datetime(df["Date"], format="%d/%m/%Y")
    # last close of each day = end-of-day price
    daily = df.groupby("date")["Close"].last()
    return daily


def load_bars(path: str, freq: str = "1D") -> pd.Series:
    """Compress the 1-min bars to ANY frequency, not just daily.

    WHY THIS EXISTS
    The daily-close study found no cointegration at all: p-values across ~215 sector
    pairs came back uniformly distributed, which is the signature of "nothing here".
    But mean reversion in liquid futures is generated by market-making and liquidity
    provision, which operate over MINUTES TO HOURS. There is no strong reason to expect
    that structure to survive out to a daily horizon. The minute bars were being thrown
    away; this reads them at a chosen resolution instead.

    NSE equity futures trade 09:15-15:30, so:
        freq="1D"    ->    1 bar/day   ~250 bars/year   (the original study)
        freq="1h"    ->   ~6 bars/day  ~1500 bars/year
        freq="30min" ->  ~12 bars/day  ~3000 bars/year
        freq="15min" ->  ~25 bars/day  ~6000 bars/year

    More bars means ADF has far more POWER -- it is much less likely to miss genuine
    mean reversion. That cuts both ways: it is a fairer test, not a friendlier one.

    @param freq  any pandas offset alias: "1D", "1h", "30min", "15min", "5min"
    @return Series indexed by bar timestamp, value = last traded price in that bar.
            Empty buckets (overnight, weekends, halts) are DROPPED, not forward-filled.
            A bar with no trade is not a price, and feeding a flat forward-filled run
            into ADF fakes mean reversion.
    """
    df = pd.read_csv(path, usecols=["Date", "Time", "Close", "Volume"])

    if freq.upper() in ("1D", "D"):
        df["date"] = pd.to_datetime(df["Date"], format="%d/%m/%Y")
        return df.groupby("date")["Close"].last()

    # combine the dd/mm/yyyy date with the HH:MM:SS time into one timestamp
    stamp = pd.to_datetime(df["Date"] + " " + df["Time"], format="%d/%m/%Y %H:%M:%S")
    df = df.set_index(stamp)

    return df["Close"].resample(freq).last().dropna()


def load_panel(folder: str, only_near_month: bool = True,
               tickers: list | None = None, freq: str = "1D") -> pd.DataFrame:
    """
    Build a close panel from all near-month futures files in `folder`.

    tickers: optional whitelist (e.g. only the ones in your sectors.py). If
             given, we only load those - much faster than loading all ~220.
    freq:    bar size. "1D" reproduces the original daily study exactly. "1h",
             "30min" etc. resample the underlying 1-min bars instead.
    Returns DataFrame: rows = timestamps, cols = tickers, values = close.
    """
    pattern = "*_-I.csv" if only_near_month else "*.csv" # String "*-I.csv" or *

    #Create files, a list of all relevant file paths
    files = sorted(glob.glob(os.path.join(folder, pattern)))
    #  /Users/.../quant_trading/derived_data/futures/*_-I.csv
    # glob.glob searches the disk, returns a list of file paths that match
    # ['/Users...futures/360ONE_-I.csv',
    #'/Users...futures/AARTIIND_-I.csv...]

    # fall back to ALL csvs if the near-month naming convention is not being used.
    # ticker = filename, so any naming scheme works -- the _-I suffix is an NSE
    # convention, not a requirement.
    if not files and only_near_month:
        files = sorted(glob.glob(os.path.join(folder, "*.csv")))

    if not files:
        raise FileNotFoundError(f"No .csv files in {folder}")

    closes = {}
    for f in files:
        ticker = _clean_ticker(f)
        if tickers is not None and ticker not in tickers:
            continue
        try:
            closes[ticker] = load_bars(f, freq=freq)
             # closes = {"HDFC" : 
             #  2023-01-02    1631.45
             #  2023-01-03    1642.10...
             #   , "AXIS" : ... }
        except Exception as e:
            print(f"  skipped {ticker}: {e}")

    panel = pd.DataFrame(closes).sort_index()
    return panel


def health_check(close: pd.DataFrame) -> None:
    # close.shape[1] = number of columns = number of stocks
    print(f"  num stocks      : {close.shape[1]}")
    # close.shape[0] = number of rows = number of trading days
    print(f"  num trading days: {close.shape[0]}")
    # close.index.min(), is min of dates, date() trims time
    print(f"  date range  : {close.index.min().date()} -> {close.index.max().date()}")
    print(f"  missing vals: {close.isna().sum().sum()}")

    # Percent change of a stock from previous day
    # pct_change() is a built-in pandas method: for each row, it computes 
    # the percent change from the row directly above it
    daily_ret = close.pct_change()    

     # Count number of stocks that had a one day percent change of > 40%
    cliffs = (daily_ret.abs() > 0.40).sum().sum()

    # Print cliffs and give flag warning in case cliffs > 0
    flag = "  <-- likely stock splits (corporate actions) to handle later" if cliffs else ""
    print(f"  >40% 1-day moves: {cliffs}{flag}")

if __name__ == "__main__":
    # Output for load_daily_close()
    path = "/Users/ashankawasthy/Desktop/quant_trading/derived_data/futures/AMBER_-I.csv"
    daily = load_daily_close(path)
    print(daily)

    # Output for load_panel()
    folder = "/Users/ashankawasthy/Desktop/quant_trading/derived_data/futures"
    panel = load_panel(folder, tickers=["AMBER", "HDFCBANK", "TCS"])
    print(panel.head())      # first 5 rows
    print()
    print(panel.tail())      # last 5 rows
    print()
    print("shape:", panel.shape)   # (days, stocks)